### ISSUE TITLE
Fill me!

### ISSUE THREAD

**Issue by tortinator** [potassco/clingomil#1]
Only a full repo, is a good repo :)

PS This is only a todo item, so that we don't forget :1st_place_medal:

**Comment by keraJLi** [comment]
Oops, I thought I was pushing here all along. Updated my remote branch!

**Comment by keraJLi** [comment]
Maybe I've closed the issue prematurely. Do you want me to push to the main branch? Otherwise you it would be nice if you made master the default branch.

**Comment by tortinator** [comment]
Thanks for getting back! It seems that when the repo was created, github already switched from master to main, as a default.\
And I overlooked this too, when raising the issue. 
Let's wait for @javier-romero to comment and then simply remove `main` and declare `master` as the default branch, and we're back in business :)

**Comment by tortinator** [comment]
@javier-romero just to ping you again :1st_place_medal:

**Comment by javier-romero** [comment]
Sorry for the delay, and thanks for caring!

I removed ``main`` and declared ``master`` as the default branch.
